### ISSUE TITLE
Feature Request - Customize characters shown around song name

### ISSUE THREAD

**Issue by lucasburlingham** [cliffniff/media-controls#5]
Saw your extension on Reddit, thanks!

I don't know how much of a hassle this may be to implement, but could you add a setting to replace the vertical pipes shown around the song title to a character of choice (such as parenthesis or even a space to 'disable')? I know that I could change it myself and install from source, but I think this may be a nice addition.

This is where I found the vertical pipes being outputted:
https://github.com/cliffniff/media-controls/blob/a0855ede73ce98b02f40b842a2bd73bb43a0acbe/extension.js#L328

Will be working on a pull request to implement this, feel free to reject.

Thanks again!

**Comment by cliffniff** [comment]
That would be a nice feature. If you are working on it, I'll be looking forward to it or else I'll try and implement it. Thanks for replying!

**Comment by cliffniff** [comment]
Also please update your fork with my recent commit, I changed the implementation of the pipes in that because of a feature I am gonna add in the future.

https://github.com/cliffniff/media-controls/blob/a55d05a12b58400de6f8e0ea2ad58444ed646207/extension.js#L80-L81
https://github.com/cliffniff/media-controls/blob/a55d05a12b58400de6f8e0ea2ad58444ed646207/extension.js#L484-L494

Hope this helps and thank you!

**Comment by cliffniff** [comment]
I added the feature in the latest update. So I guess I will close this issue. Anyways thanks for replying. If there are anymore features you need, don't hesitate to request!

**Comment by lucasburlingham** [comment]
Thanks!
